
title: Hatem Khattab
email: 
description: >- # this means to ignore newlines until "baseurl:"
 The home page for Hatem Khattab
baseurl: 
url:
theme: 
plugins:
defaults:
  - scope:
      path: "assets/images"
    values:
      image: true
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/